server:
  port: 8005

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: invoice-service
          uri: lb://invoice-service
          predicates:
            - Path=/invoices/**
        - id: payments-service
          uri: lb://payments-service
          predicates:
            - Path=/payments/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
